import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Music Player",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  
  return (
    <html lang="en" style={{overflow:'hidden',width:'10vw',height:'10vh'}} >
      <body style={{overflow:'hidden',width:'100dvw',height:'100dvh',position:'relative'}}
        className={`${geistSans.variable} ${geistMono.variable} antialiased pb-[10vh] md:pb-0  `}
      >
        {children}
      </body>
    </html>
  );
}
